exec AddTrack @description='DBA'
exec AddTrack @description='BI'
exec AddTrack @description='Development'
exec AddTrack @description='Performance'
exec AddTrack @description='Other'
exec AddTrack @description='Optimization'